maintel:
  driver_type: feature_scheduler
  mode: ADVANCE
  startup_type: COLD
  startup_database: /home/saluser/rubin_sim_data/preop_lsst_fbs_observations.sql
  models:
    observatory_model:
      camera:
        filter_max_changes_burst_num: 1000000
        filter_max_changes_avg_num: 30000
      park:
        filter_position: r
      telescope:
        azimuth_maxspeed: 1.0
        azimuth_accel: 1.0
        altitude_maxspeed: 1.0
        altitude_accel: 1.0
        settle_time: 3.0
      optics_loop_corr:
        tel_optics_cl_alt_limit:
          - 0.0
          - 9.0
          - 90.0
        tel_optics_cl_delay:
          - 0.0
          - 36.0
  driver_configuration:
    parameters:
      night_boundary: -10.0
    stop_tracking_observing_script_name: maintel/stop_tracking.py
  feature_scheduler_driver_configuration:
    observation_database_name: /home/saluser/rubin_sim_data/preops_lsst_fbs_observations.sql
    scheduler_config: /net/obs-env/auto_base_packages/ts_config_scheduler/Scheduler/feature_scheduler/maintel/fbs_config_lsst_survey.py
  telemetry:
    lfa_client:
      source: DREAM
      delta_time: 300.0
      db_name: efd
    streams:
      - name: seeing
        efd_table: lsst.sal.DIMM.logevent_dimmMeasurement
        efd_columns:
          - fwhm
        efd_delta_time: 300.0
        fill_value: 1.0
      - name: wind_speed
        efd_table: lsst.sal.ESS.airFlow
        efd_columns:
          - speed
        efd_delta_time: 300.0
        fill_value: 0.0
        csc_index: 301
      - name: wind_direction
        efd_table: lsst.sal.ESS.airFlow
        efd_columns:
          - direction
        efd_delta_time: 300.0
        fill_value: 0.0
        csc_index: 301
